### ISSUE TITLE
Appears impossible to provide a custom template pack path?

### ISSUE THREAD

**Issue by erulabs** [rackerlabs/fastfood#21]
It seems --template-pack does not work...

```
$ fastfood --template-pack=~/code/seandons_templatepack --cookbooks=. build fastfood.json
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fastfood/shell.py", line 163, in main
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/fastfood/shell.py", line 57, in _fastfood_build
    args.cookbooks, cookbook_path=args.cookbook)
  File "/usr/local/lib/python2.7/site-packages/fastfood/food.py", line 52, in build_cookbook
    cookbook_name, templatepack, cookbooks_home, force=force)
  File "/usr/local/lib/python2.7/site-packages/fastfood/food.py", line 178, in create_new_cookbook
    tmppack = pack.TemplatePack(templatepack)
  File "/usr/local/lib/python2.7/site-packages/fastfood/pack.py", line 33, in __init__
    % self.path)
ValueError: Templatepack dir /Users/sean6011/code/seandons_templatepack does not exist.
ValueError('Templatepack dir /Users/sean6011/code/seandons_templatepack does not exist.',)
```

```
$ ls -al /Users/sean6011/code/seandons_templatepack
total 24
drwxr-xr-x   8 sean6011  RACKSPACE\Domain Users   272 Feb 23 17:11 .
drwxr-xr-x  44 sean6011  RACKSPACE\Domain Users  1496 Feb 23 16:41 ..
drwxr-xr-x  13 sean6011  RACKSPACE\Domain Users   442 Feb 23 16:39 .git
-rw-r--r--   1 sean6011  RACKSPACE\Domain Users  1093 Feb  4 17:05 .rubocop.yml
-rw-r--r--   1 sean6011  RACKSPACE\Domain Users  2023 Feb 17 15:43 README.md
drwxr-xr-x  14 sean6011  RACKSPACE\Domain Users   476 Feb 23 17:12 base
-rw-r--r--   1 sean6011  RACKSPACE\Domain Users  2230 Feb 17 15:46 manifest.json
drwxr-xr-x  22 sean6011  RACKSPACE\Domain Users   748 Feb 17 14:54 stencils
```

Going to dig around in the code a bit, but that directory clearly does exist...
```
        self.path = utils.normalize_path(path)
        if not os.path.isdir(path):
            raise ValueError("Templatepack dir %s does not exist."
                             % self.path)
```

Seems strange that we normalize the path, and then don't use the normalized value? I'd guess this should be modified to read:

```
        self.path = utils.normalize_path(path)
        if not os.path.isdir(self.path):
            raise ValueError("Templatepack dir %s does not exist."
                             % self.path)
```

**Comment by samstav** [comment]
Closed by https://github.com/rackerlabs/fastfood/pull/22
