### ISSUE TITLE
fastfood build gives a traceback

### ISSUE THREAD

**Issue by brint** [rackerlabs/fastfood#62]
When running this with `fastfood build`, we receive the following traceback:

```
$ fastfood build test/fixtures/nginx_cookbook.json 
⁉️  Unexpected error. Please report this traceback.
Traceback (most recent call last):
  File "/Users/brint/src/fastfood/.ff/lib/python2.7/site-packages/fastfood-0.1.9-py2.7.egg/fastfood/shell.py", line 274, in main
    args.func(args)
  File "/Users/brint/src/fastfood/.ff/lib/python2.7/site-packages/fastfood-0.1.9-py2.7.egg/fastfood/shell.py", line 69, in _fastfood_build
    args.cookbooks, cookbook_path=args.cookbook)
  File "/Users/brint/src/fastfood/.ff/lib/python2.7/site-packages/fastfood-0.1.9-py2.7.egg/fastfood/food.py", line 58, in build_cookbook
    cookbook_name, templatepack, cookbooks_home, force=force)
  File "/Users/brint/src/fastfood/.ff/lib/python2.7/site-packages/fastfood-0.1.9-py2.7.egg/fastfood/food.py", line 186, in create_new_cookbook
    filetable = templating.render_templates(*template_files, **template_map)
  File "/Users/brint/src/fastfood/.ff/lib/python2.7/site-packages/fastfood-0.1.9-py2.7.egg/fastfood/templating.py", line 46, in render_templates
    return list(render_templates_generator(*files, **template_map))
  File "/Users/brint/src/fastfood/.ff/lib/python2.7/site-packages/fastfood-0.1.9-py2.7.egg/fastfood/templating.py", line 68, in render_templates_generator
    result = template.render(**template_map)
  File "/Users/brint/src/fastfood/.ff/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/brint/src/fastfood/.ff/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 3, in top-level template code
  File "/Users/brint/src/fastfood/.ff/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/environment.py", line 378, in getitem
    return obj[argument]
UndefinedError: 'options' is undefined
```

I'm not sure if this is a user error in how we're building things out. Here's what `test/fixtures/nginx_cookbook.json` looks like for reference:

```
{
  "name": "nginx_cookbook",
  "stencils": [
    {
      "stencil_set": "nginx",
      "stencil": "nginx",
      "name": "example.com"
    }
  ]
}
```

**Comment by dude051** [comment]
Getting this same error on trying to use new command, was working until after I upgraded this morning.

**Comment by brint** [comment]
I've tested with master and all versions in pip (0.0.9, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9), and it looks like they may all be impacted.

**Comment by samstav** [comment]
This must be due to a change in the templatepack.
