### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'pop'

### ISSUE THREAD

**Issue by martinb3** [rackerlabs/fastfood#64]
I'm writing a stencil, and it seems like we could use more error checking for this piece:
```
⁉️  Unexpected error. Please report this traceback.
Traceback (most recent call last):
  File "/home/mart6985/src/virtualenv/fastfood/local/lib/python2.7/site-packages/fastfood/shell.py", line 274, in main
    args.func(args)
  File "/home/mart6985/src/virtualenv/fastfood/local/lib/python2.7/site-packages/fastfood/shell.py", line 69, in _fastfood_build
    args.cookbooks, cookbook_path=args.cookbook)
  File "/home/mart6985/src/virtualenv/fastfood/local/lib/python2.7/site-packages/fastfood/food.py", line 62, in build_cookbook
    stencil_set = stencil.pop('stencil_set')
AttributeError: 'unicode' object has no attribute 'pop'
```

The error is coming from a fairly simple stencil:
```
{
  "id": "java",
  "description": "Install Java from the upstream java community cookbook",
  "default_stencil": "java",
  "api": 1,
  "dependencies": {
    "java": {}
  },
  "options": {
    "name": {
      "help": "Name of the recipe to create",
      "default": "java"
    }
  },
  "stencils": {
    "java": {
      "files": {
        "recipes/java.rb": "recipes/_java.jinja2"
      },
      "options": {
      }
    }
  }
}
```

**Comment by samstav** [comment]
Thanks for reporting this. With all the json floating around, looks like its time for us to integrate some friendly validation using something like [voluptuous](https://pypi.python.org/pypi/voluptuous)

I think the specific error here is because the `stencils` property is supposed to be an array.

**Comment by martinb3** [comment]
It appears that some of the other base stencils like 'apache' aren't arrays, but pass:
```
  "stencils": {
    "apache": {
      "files": {
        "recipes/<NAME>.rb": "recipes/_apache.rb.jinja2",
        "templates/default/apache/apache2.conf.erb": "templates/default/apache2.conf.erb",
        "templates/default/apache/mpm_event.conf.erb": "templates/default/mpm_event.conf.erb",
        "templates/default/apache/ports.conf.erb": "templates/default/ports.conf.erb",
        "test/integration/default/serverspec/<NAME>_spec.rb": "test/integration/default/serverspec/apache_spec.rb"
      },
      "options": {
      }
    }
  }
```

**Comment by samstav** [comment]
Oh, interesting....

**Comment by martinb3** [comment]
@samstav pointed me at [this section of the docs](https://github.com/rackerlabs/fastfood#build), with a working example. Opening a separate issue to do better valid/well-formed checks before attempting to access the data.
