### ISSUE TITLE
fastfood doesn't work on a centos 6 server.

### ISSUE THREAD

**Issue by racker-markh** [rackerlabs/fastfood#96]
I installed fastfood on a CentOS release 6.6 and 'fastfood list' fails with the following error:

```
[devops@ws-markhyde ~]$ fastfood list
Traceback (most recent call last):
  File "/home/devops/venv/bin/fastfood", line 7, in <module>
    from fastfood.shell import main
  File "/home/devops/venv/lib/python2.6/site-packages/fastfood/shell.py", line 231
    args.options = {k: v for k, v in args.options}
                           ^
SyntaxError: invalid syntax

```
Centos 6 uses Python 2.6 by default and I believe this is why it is failing.

I confirmed that I was able to install it and have it run OK on fedora22 (which uses py27) and also installed the python2.7 package from IUS on my centos box and installed fastfood in a virtualenv and this also works.

So could you either 
  - add something to the pip install to prevent it installing for python <2.7  and update documentation to this effect
OR 
  - get it to work with earlier versions?

Regards
Mark

**Comment by samstav** [comment]
I think we can easily get this to work with python 2.6. I checked our only dependency, Jinja2, and it supports 2.6: https://github.com/mitsuhiko/jinja2/blob/2.8/setup.py#L61

Looks like the first item is the lack of dict comprehensions in python 2.6. We can turn this into a normal `for` loop, or do this:

http://stackoverflow.com/a/21069676/1547030

I might not have time to make the changes anytime soon, but I will keep my eye on this issue and submit a PR if I get a chance.
